# coding: utf-8

"""
    Puupee API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import puupee-api
from puupee-api.api.profile_api import ProfileApi  # noqa: E501
from puupee-api.rest import ApiException


class TestProfileApi(unittest.TestCase):
    """ProfileApi unit test stubs"""

    def setUp(self):
        self.api = puupee-api.api.profile_api.ProfileApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_account_my_profile_change_password_post(self):
        """Test case for api_account_my_profile_change_password_post

        """
        pass

    def test_api_account_my_profile_get(self):
        """Test case for api_account_my_profile_get

        """
        pass

    def test_api_account_my_profile_put(self):
        """Test case for api_account_my_profile_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
