# coding: utf-8

"""
    Puupee API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import puupee-api
from puupee-api.api.device_api import DeviceApi  # noqa: E501
from puupee-api.rest import ApiException


class TestDeviceApi(unittest.TestCase):
    """DeviceApi unit test stubs"""

    def setUp(self):
        self.api = puupee-api.api.device_api.DeviceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_app_device_bind_post(self):
        """Test case for api_app_device_bind_post

        """
        pass

    def test_api_app_device_delete(self):
        """Test case for api_app_device_delete

        """
        pass

    def test_api_app_device_get(self):
        """Test case for api_app_device_get

        """
        pass

    def test_api_app_device_refresh_post(self):
        """Test case for api_app_device_refresh_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
