# coding: utf-8

"""
    Puupee API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import puupee-api
from puupee-api.models.timing_dto import TimingDto  # noqa: E501
from puupee-api.rest import ApiException

class TestTimingDto(unittest.TestCase):
    """TimingDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TimingDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = puupee-api.models.timing_dto.TimingDto()  # noqa: E501
        if include_optional :
            return TimingDto(
                time_zone = puupee-api.models.time_zone.TimeZone(
                    iana = puupee-api.models.iana_time_zone.IanaTimeZone(
                        time_zone_name = '', ), 
                    windows = puupee-api.models.windows_time_zone.WindowsTimeZone(
                        time_zone_id = '', ), )
            )
        else :
            return TimingDto(
        )

    def testTimingDto(self):
        """Test TimingDto"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
