# coding: utf-8

"""
    Puupee API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import puupee-api
from puupee-api.models.controller_interface_api_description_model import ControllerInterfaceApiDescriptionModel  # noqa: E501
from puupee-api.rest import ApiException

class TestControllerInterfaceApiDescriptionModel(unittest.TestCase):
    """ControllerInterfaceApiDescriptionModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ControllerInterfaceApiDescriptionModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = puupee-api.models.controller_interface_api_description_model.ControllerInterfaceApiDescriptionModel()  # noqa: E501
        if include_optional :
            return ControllerInterfaceApiDescriptionModel(
                type = '', 
                name = '', 
                methods = [
                    puupee-api.models.interface_method_api_description_model.InterfaceMethodApiDescriptionModel(
                        name = '', 
                        parameters_on_method = [
                            puupee-api.models.method_parameter_api_description_model.MethodParameterApiDescriptionModel(
                                name = '', 
                                type_as_string = '', 
                                type = '', 
                                type_simple = '', 
                                is_optional = True, 
                                default_value = null, )
                            ], 
                        return_value = puupee-api.models.return_value_api_description_model.ReturnValueApiDescriptionModel(
                            type = '', 
                            type_simple = '', ), )
                    ]
            )
        else :
            return ControllerInterfaceApiDescriptionModel(
        )

    def testControllerInterfaceApiDescriptionModel(self):
        """Test ControllerInterfaceApiDescriptionModel"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
