# coding: utf-8

"""
    Puupee API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import puupee-api
from puupee-api.api.simple_data_api import SimpleDataApi  # noqa: E501
from puupee-api.rest import ApiException


class TestSimpleDataApi(unittest.TestCase):
    """SimpleDataApi unit test stubs"""

    def setUp(self):
        self.api = puupee-api.api.simple_data_api.SimpleDataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_app_simple_data_get(self):
        """Test case for api_app_simple_data_get

        """
        pass

    def test_api_app_simple_data_id_delete(self):
        """Test case for api_app_simple_data_id_delete

        """
        pass

    def test_api_app_simple_data_id_get(self):
        """Test case for api_app_simple_data_id_get

        """
        pass

    def test_api_app_simple_data_save_post(self):
        """Test case for api_app_simple_data_save_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
