# coding: utf-8

"""
    Puupee API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import puupee-api
from puupee-api.api.app_pricing_api import AppPricingApi  # noqa: E501
from puupee-api.rest import ApiException


class TestAppPricingApi(unittest.TestCase):
    """AppPricingApi unit test stubs"""

    def setUp(self):
        self.api = puupee-api.api.app_pricing_api.AppPricingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_app_app_pricing_by_app_id_app_id_get(self):
        """Test case for api_app_app_pricing_by_app_id_app_id_get

        """
        pass

    def test_api_app_app_pricing_get(self):
        """Test case for api_app_app_pricing_get

        """
        pass

    def test_api_app_app_pricing_id_delete(self):
        """Test case for api_app_app_pricing_id_delete

        """
        pass

    def test_api_app_app_pricing_id_get(self):
        """Test case for api_app_app_pricing_id_get

        """
        pass

    def test_api_app_app_pricing_id_put(self):
        """Test case for api_app_app_pricing_id_put

        """
        pass

    def test_api_app_app_pricing_post(self):
        """Test case for api_app_app_pricing_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
