# coding: utf-8

"""
    Puupee API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import puupee-api
from puupee-api.models.application_localization_configuration_dto import ApplicationLocalizationConfigurationDto  # noqa: E501
from puupee-api.rest import ApiException

class TestApplicationLocalizationConfigurationDto(unittest.TestCase):
    """ApplicationLocalizationConfigurationDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ApplicationLocalizationConfigurationDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = puupee-api.models.application_localization_configuration_dto.ApplicationLocalizationConfigurationDto()  # noqa: E501
        if include_optional :
            return ApplicationLocalizationConfigurationDto(
                values = {
                    'key' : {
                        'key' : ''
                        }
                    }, 
                resources = {
                    'key' : puupee-api.models.application_localization_resource_dto.ApplicationLocalizationResourceDto(
                        texts = {
                            'key' : ''
                            }, 
                        base_resources = [
                            ''
                            ], )
                    }, 
                languages = [
                    puupee-api.models.language_info.LanguageInfo(
                        culture_name = '', 
                        ui_culture_name = '', 
                        display_name = '', 
                        two_letter_iso_language_name = '', 
                        flag_icon = '', )
                    ], 
                current_culture = puupee-api.models.current_culture_dto.CurrentCultureDto(
                    display_name = '', 
                    english_name = '', 
                    three_letter_iso_language_name = '', 
                    two_letter_iso_language_name = '', 
                    is_right_to_left = True, 
                    culture_name = '', 
                    name = '', 
                    native_name = '', 
                    date_time_format = puupee-api.models.date_time_format_dto.DateTimeFormatDto(
                        calendar_algorithm_type = '', 
                        date_time_format_long = '', 
                        short_date_pattern = '', 
                        full_date_time_pattern = '', 
                        date_separator = '', 
                        short_time_pattern = '', 
                        long_time_pattern = '', ), ), 
                default_resource_name = '', 
                languages_map = {
                    'key' : [
                        puupee-api.models.name_value.NameValue(
                            name = '', 
                            value = '', )
                        ]
                    }, 
                language_files_map = {
                    'key' : [
                        puupee-api.models.name_value.NameValue(
                            name = '', 
                            value = '', )
                        ]
                    }
            )
        else :
            return ApplicationLocalizationConfigurationDto(
        )

    def testApplicationLocalizationConfigurationDto(self):
        """Test ApplicationLocalizationConfigurationDto"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
