# coding: utf-8

"""
    Puupee API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import puupee-api
from puupee-api.models.create_or_update_app_release_dto import CreateOrUpdateAppReleaseDto  # noqa: E501
from puupee-api.rest import ApiException

class TestCreateOrUpdateAppReleaseDto(unittest.TestCase):
    """CreateOrUpdateAppReleaseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreateOrUpdateAppReleaseDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = puupee-api.models.create_or_update_app_release_dto.CreateOrUpdateAppReleaseDto()  # noqa: E501
        if include_optional :
            return CreateOrUpdateAppReleaseDto(
                version = '', 
                version_name = '', 
                version_code = 56, 
                notes = '', 
                platform = '', 
                key = '', 
                rapid_code = '', 
                size = 56, 
                md5 = '', 
                slice_md5 = '', 
                product_type = '', 
                is_force_update = True, 
                app_id = '', 
                is_enabled = True, 
                channel = '', 
                environment = ''
            )
        else :
            return CreateOrUpdateAppReleaseDto(
        )

    def testCreateOrUpdateAppReleaseDto(self):
        """Test CreateOrUpdateAppReleaseDto"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
