# coding: utf-8

"""
    Puupee API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import puupee-api
from puupee-api.api.abp_tenant_api import AbpTenantApi  # noqa: E501
from puupee-api.rest import ApiException


class TestAbpTenantApi(unittest.TestCase):
    """AbpTenantApi unit test stubs"""

    def setUp(self):
        self.api = puupee-api.api.abp_tenant_api.AbpTenantApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_abp_multi_tenancy_tenants_by_id_id_get(self):
        """Test case for api_abp_multi_tenancy_tenants_by_id_id_get

        """
        pass

    def test_api_abp_multi_tenancy_tenants_by_name_name_get(self):
        """Test case for api_abp_multi_tenancy_tenants_by_name_name_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
