# coding: utf-8

"""
    Puupee API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.int32_set_key_value_dto import Int32SetKeyValueDto
from openapi_client import configuration


class TestInt32SetKeyValueDto(unittest.TestCase):
    """Int32SetKeyValueDto unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
