# coding: utf-8

"""
    Puupee API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.identity_user_update_roles_dto import IdentityUserUpdateRolesDto
from openapi_client import configuration


class TestIdentityUserUpdateRolesDto(unittest.TestCase):
    """IdentityUserUpdateRolesDto unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
