# coding: utf-8

"""
    Puupee API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import puupee-api
from puupee-api.model.update_email_settings_dto import UpdateEmailSettingsDto
from puupee-api import configuration


class TestUpdateEmailSettingsDto(unittest.TestCase):
    """UpdateEmailSettingsDto unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
