# coding: utf-8

"""
    Puupee API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.decimal_key_value import DecimalKeyValue
from openapi_client import configuration


class TestDecimalKeyValue(unittest.TestCase):
    """DecimalKeyValue unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
