# coding: utf-8

"""
    Puupee API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

import unittest

import puupee-api
from puupee-api.model.profile_dto import ProfileDto
from puupee-api import configuration


class TestProfileDto(unittest.TestCase):
    """ProfileDto unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
