# coding: utf-8

"""
    Puupee API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from puupee-api.configuration import Configuration


class IdentityUserCreateDto(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'extra_properties': 'dict[str, object]',
        'user_name': 'str',
        'name': 'str',
        'surname': 'str',
        'email': 'str',
        'phone_number': 'str',
        'is_active': 'bool',
        'lockout_enabled': 'bool',
        'role_names': 'list[str]',
        'password': 'str'
    }

    attribute_map = {
        'extra_properties': 'extraProperties',
        'user_name': 'userName',
        'name': 'name',
        'surname': 'surname',
        'email': 'email',
        'phone_number': 'phoneNumber',
        'is_active': 'isActive',
        'lockout_enabled': 'lockoutEnabled',
        'role_names': 'roleNames',
        'password': 'password'
    }

    def __init__(self, extra_properties=None, user_name=None, name=None, surname=None, email=None, phone_number=None, is_active=None, lockout_enabled=None, role_names=None, password=None, local_vars_configuration=None):  # noqa: E501
        """IdentityUserCreateDto - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._extra_properties = None
        self._user_name = None
        self._name = None
        self._surname = None
        self._email = None
        self._phone_number = None
        self._is_active = None
        self._lockout_enabled = None
        self._role_names = None
        self._password = None
        self.discriminator = None

        self.extra_properties = extra_properties
        self.user_name = user_name
        self.name = name
        self.surname = surname
        self.email = email
        self.phone_number = phone_number
        if is_active is not None:
            self.is_active = is_active
        if lockout_enabled is not None:
            self.lockout_enabled = lockout_enabled
        self.role_names = role_names
        self.password = password

    @property
    def extra_properties(self):
        """Gets the extra_properties of this IdentityUserCreateDto.  # noqa: E501


        :return: The extra_properties of this IdentityUserCreateDto.  # noqa: E501
        :rtype: dict[str, object]
        """
        return self._extra_properties

    @extra_properties.setter
    def extra_properties(self, extra_properties):
        """Sets the extra_properties of this IdentityUserCreateDto.


        :param extra_properties: The extra_properties of this IdentityUserCreateDto.  # noqa: E501
        :type extra_properties: dict[str, object]
        """

        self._extra_properties = extra_properties

    @property
    def user_name(self):
        """Gets the user_name of this IdentityUserCreateDto.  # noqa: E501


        :return: The user_name of this IdentityUserCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._user_name

    @user_name.setter
    def user_name(self, user_name):
        """Sets the user_name of this IdentityUserCreateDto.


        :param user_name: The user_name of this IdentityUserCreateDto.  # noqa: E501
        :type user_name: str
        """
        if self.local_vars_configuration.client_side_validation and user_name is None:  # noqa: E501
            raise ValueError("Invalid value for `user_name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                user_name is not None and len(user_name) > 256):
            raise ValueError("Invalid value for `user_name`, length must be less than or equal to `256`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                user_name is not None and len(user_name) < 0):
            raise ValueError("Invalid value for `user_name`, length must be greater than or equal to `0`")  # noqa: E501

        self._user_name = user_name

    @property
    def name(self):
        """Gets the name of this IdentityUserCreateDto.  # noqa: E501


        :return: The name of this IdentityUserCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this IdentityUserCreateDto.


        :param name: The name of this IdentityUserCreateDto.  # noqa: E501
        :type name: str
        """
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) > 64):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `64`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 0):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `0`")  # noqa: E501

        self._name = name

    @property
    def surname(self):
        """Gets the surname of this IdentityUserCreateDto.  # noqa: E501


        :return: The surname of this IdentityUserCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._surname

    @surname.setter
    def surname(self, surname):
        """Sets the surname of this IdentityUserCreateDto.


        :param surname: The surname of this IdentityUserCreateDto.  # noqa: E501
        :type surname: str
        """
        if (self.local_vars_configuration.client_side_validation and
                surname is not None and len(surname) > 64):
            raise ValueError("Invalid value for `surname`, length must be less than or equal to `64`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                surname is not None and len(surname) < 0):
            raise ValueError("Invalid value for `surname`, length must be greater than or equal to `0`")  # noqa: E501

        self._surname = surname

    @property
    def email(self):
        """Gets the email of this IdentityUserCreateDto.  # noqa: E501


        :return: The email of this IdentityUserCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this IdentityUserCreateDto.


        :param email: The email of this IdentityUserCreateDto.  # noqa: E501
        :type email: str
        """
        if self.local_vars_configuration.client_side_validation and email is None:  # noqa: E501
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                email is not None and len(email) > 256):
            raise ValueError("Invalid value for `email`, length must be less than or equal to `256`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                email is not None and len(email) < 0):
            raise ValueError("Invalid value for `email`, length must be greater than or equal to `0`")  # noqa: E501

        self._email = email

    @property
    def phone_number(self):
        """Gets the phone_number of this IdentityUserCreateDto.  # noqa: E501


        :return: The phone_number of this IdentityUserCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number):
        """Sets the phone_number of this IdentityUserCreateDto.


        :param phone_number: The phone_number of this IdentityUserCreateDto.  # noqa: E501
        :type phone_number: str
        """
        if (self.local_vars_configuration.client_side_validation and
                phone_number is not None and len(phone_number) > 16):
            raise ValueError("Invalid value for `phone_number`, length must be less than or equal to `16`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                phone_number is not None and len(phone_number) < 0):
            raise ValueError("Invalid value for `phone_number`, length must be greater than or equal to `0`")  # noqa: E501

        self._phone_number = phone_number

    @property
    def is_active(self):
        """Gets the is_active of this IdentityUserCreateDto.  # noqa: E501


        :return: The is_active of this IdentityUserCreateDto.  # noqa: E501
        :rtype: bool
        """
        return self._is_active

    @is_active.setter
    def is_active(self, is_active):
        """Sets the is_active of this IdentityUserCreateDto.


        :param is_active: The is_active of this IdentityUserCreateDto.  # noqa: E501
        :type is_active: bool
        """

        self._is_active = is_active

    @property
    def lockout_enabled(self):
        """Gets the lockout_enabled of this IdentityUserCreateDto.  # noqa: E501


        :return: The lockout_enabled of this IdentityUserCreateDto.  # noqa: E501
        :rtype: bool
        """
        return self._lockout_enabled

    @lockout_enabled.setter
    def lockout_enabled(self, lockout_enabled):
        """Sets the lockout_enabled of this IdentityUserCreateDto.


        :param lockout_enabled: The lockout_enabled of this IdentityUserCreateDto.  # noqa: E501
        :type lockout_enabled: bool
        """

        self._lockout_enabled = lockout_enabled

    @property
    def role_names(self):
        """Gets the role_names of this IdentityUserCreateDto.  # noqa: E501


        :return: The role_names of this IdentityUserCreateDto.  # noqa: E501
        :rtype: list[str]
        """
        return self._role_names

    @role_names.setter
    def role_names(self, role_names):
        """Sets the role_names of this IdentityUserCreateDto.


        :param role_names: The role_names of this IdentityUserCreateDto.  # noqa: E501
        :type role_names: list[str]
        """

        self._role_names = role_names

    @property
    def password(self):
        """Gets the password of this IdentityUserCreateDto.  # noqa: E501


        :return: The password of this IdentityUserCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this IdentityUserCreateDto.


        :param password: The password of this IdentityUserCreateDto.  # noqa: E501
        :type password: str
        """
        if self.local_vars_configuration.client_side_validation and password is None:  # noqa: E501
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                password is not None and len(password) > 128):
            raise ValueError("Invalid value for `password`, length must be less than or equal to `128`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                password is not None and len(password) < 0):
            raise ValueError("Invalid value for `password`, length must be greater than or equal to `0`")  # noqa: E501

        self._password = password

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IdentityUserCreateDto):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IdentityUserCreateDto):
            return True

        return self.to_dict() != other.to_dict()
