# coding: utf-8

"""
    Puupee API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from puupee-api.configuration import Configuration


class ModuleApiDescriptionModel(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'root_path': 'str',
        'remote_service_name': 'str',
        'controllers': 'dict[str, ControllerApiDescriptionModel]'
    }

    attribute_map = {
        'root_path': 'rootPath',
        'remote_service_name': 'remoteServiceName',
        'controllers': 'controllers'
    }

    def __init__(self, root_path=None, remote_service_name=None, controllers=None, local_vars_configuration=None):  # noqa: E501
        """ModuleApiDescriptionModel - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._root_path = None
        self._remote_service_name = None
        self._controllers = None
        self.discriminator = None

        self.root_path = root_path
        self.remote_service_name = remote_service_name
        self.controllers = controllers

    @property
    def root_path(self):
        """Gets the root_path of this ModuleApiDescriptionModel.  # noqa: E501


        :return: The root_path of this ModuleApiDescriptionModel.  # noqa: E501
        :rtype: str
        """
        return self._root_path

    @root_path.setter
    def root_path(self, root_path):
        """Sets the root_path of this ModuleApiDescriptionModel.


        :param root_path: The root_path of this ModuleApiDescriptionModel.  # noqa: E501
        :type root_path: str
        """

        self._root_path = root_path

    @property
    def remote_service_name(self):
        """Gets the remote_service_name of this ModuleApiDescriptionModel.  # noqa: E501


        :return: The remote_service_name of this ModuleApiDescriptionModel.  # noqa: E501
        :rtype: str
        """
        return self._remote_service_name

    @remote_service_name.setter
    def remote_service_name(self, remote_service_name):
        """Sets the remote_service_name of this ModuleApiDescriptionModel.


        :param remote_service_name: The remote_service_name of this ModuleApiDescriptionModel.  # noqa: E501
        :type remote_service_name: str
        """

        self._remote_service_name = remote_service_name

    @property
    def controllers(self):
        """Gets the controllers of this ModuleApiDescriptionModel.  # noqa: E501


        :return: The controllers of this ModuleApiDescriptionModel.  # noqa: E501
        :rtype: dict[str, ControllerApiDescriptionModel]
        """
        return self._controllers

    @controllers.setter
    def controllers(self, controllers):
        """Sets the controllers of this ModuleApiDescriptionModel.


        :param controllers: The controllers of this ModuleApiDescriptionModel.  # noqa: E501
        :type controllers: dict[str, ControllerApiDescriptionModel]
        """

        self._controllers = controllers

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModuleApiDescriptionModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ModuleApiDescriptionModel):
            return True

        return self.to_dict() != other.to_dict()
