# coding: utf-8

"""
    Puupee API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from puupee-api.configuration import Configuration


class ReturnValueApiDescriptionModel(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'type': 'str',
        'type_simple': 'str'
    }

    attribute_map = {
        'type': 'type',
        'type_simple': 'typeSimple'
    }

    def __init__(self, type=None, type_simple=None, local_vars_configuration=None):  # noqa: E501
        """ReturnValueApiDescriptionModel - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._type = None
        self._type_simple = None
        self.discriminator = None

        self.type = type
        self.type_simple = type_simple

    @property
    def type(self):
        """Gets the type of this ReturnValueApiDescriptionModel.  # noqa: E501


        :return: The type of this ReturnValueApiDescriptionModel.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ReturnValueApiDescriptionModel.


        :param type: The type of this ReturnValueApiDescriptionModel.  # noqa: E501
        :type type: str
        """

        self._type = type

    @property
    def type_simple(self):
        """Gets the type_simple of this ReturnValueApiDescriptionModel.  # noqa: E501


        :return: The type_simple of this ReturnValueApiDescriptionModel.  # noqa: E501
        :rtype: str
        """
        return self._type_simple

    @type_simple.setter
    def type_simple(self, type_simple):
        """Sets the type_simple of this ReturnValueApiDescriptionModel.


        :param type_simple: The type_simple of this ReturnValueApiDescriptionModel.  # noqa: E501
        :type type_simple: str
        """

        self._type_simple = type_simple

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReturnValueApiDescriptionModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ReturnValueApiDescriptionModel):
            return True

        return self.to_dict() != other.to_dict()
