# coding: utf-8

"""
    Puupee API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from puupee-api.configuration import Configuration


class SendPasswordResetCodeDto(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'email': 'str',
        'app_name': 'str',
        'return_url': 'str',
        'return_url_hash': 'str'
    }

    attribute_map = {
        'email': 'email',
        'app_name': 'appName',
        'return_url': 'returnUrl',
        'return_url_hash': 'returnUrlHash'
    }

    def __init__(self, email=None, app_name=None, return_url=None, return_url_hash=None, local_vars_configuration=None):  # noqa: E501
        """SendPasswordResetCodeDto - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._email = None
        self._app_name = None
        self._return_url = None
        self._return_url_hash = None
        self.discriminator = None

        self.email = email
        self.app_name = app_name
        self.return_url = return_url
        self.return_url_hash = return_url_hash

    @property
    def email(self):
        """Gets the email of this SendPasswordResetCodeDto.  # noqa: E501


        :return: The email of this SendPasswordResetCodeDto.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this SendPasswordResetCodeDto.


        :param email: The email of this SendPasswordResetCodeDto.  # noqa: E501
        :type email: str
        """
        if self.local_vars_configuration.client_side_validation and email is None:  # noqa: E501
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                email is not None and len(email) > 256):
            raise ValueError("Invalid value for `email`, length must be less than or equal to `256`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                email is not None and len(email) < 0):
            raise ValueError("Invalid value for `email`, length must be greater than or equal to `0`")  # noqa: E501

        self._email = email

    @property
    def app_name(self):
        """Gets the app_name of this SendPasswordResetCodeDto.  # noqa: E501


        :return: The app_name of this SendPasswordResetCodeDto.  # noqa: E501
        :rtype: str
        """
        return self._app_name

    @app_name.setter
    def app_name(self, app_name):
        """Sets the app_name of this SendPasswordResetCodeDto.


        :param app_name: The app_name of this SendPasswordResetCodeDto.  # noqa: E501
        :type app_name: str
        """
        if self.local_vars_configuration.client_side_validation and app_name is None:  # noqa: E501
            raise ValueError("Invalid value for `app_name`, must not be `None`")  # noqa: E501

        self._app_name = app_name

    @property
    def return_url(self):
        """Gets the return_url of this SendPasswordResetCodeDto.  # noqa: E501


        :return: The return_url of this SendPasswordResetCodeDto.  # noqa: E501
        :rtype: str
        """
        return self._return_url

    @return_url.setter
    def return_url(self, return_url):
        """Sets the return_url of this SendPasswordResetCodeDto.


        :param return_url: The return_url of this SendPasswordResetCodeDto.  # noqa: E501
        :type return_url: str
        """

        self._return_url = return_url

    @property
    def return_url_hash(self):
        """Gets the return_url_hash of this SendPasswordResetCodeDto.  # noqa: E501


        :return: The return_url_hash of this SendPasswordResetCodeDto.  # noqa: E501
        :rtype: str
        """
        return self._return_url_hash

    @return_url_hash.setter
    def return_url_hash(self, return_url_hash):
        """Sets the return_url_hash of this SendPasswordResetCodeDto.


        :param return_url_hash: The return_url_hash of this SendPasswordResetCodeDto.  # noqa: E501
        :type return_url_hash: str
        """

        self._return_url_hash = return_url_hash

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SendPasswordResetCodeDto):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SendPasswordResetCodeDto):
            return True

        return self.to_dict() != other.to_dict()
