# coding: utf-8

"""
    Puupee API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

from puupee-api.paths.api_app_app_by_developer.get import ApiAppAppByDeveloperGet
from puupee-api.paths.api_app_app_by_name.get import ApiAppAppByNameGet
from puupee-api.paths.api_app_app.get import ApiAppAppGet
from puupee-api.paths.api_app_app_id.delete import ApiAppAppIdDelete
from puupee-api.paths.api_app_app_id.get import ApiAppAppIdGet
from puupee-api.paths.api_app_app_id.put import ApiAppAppIdPut
from puupee-api.paths.api_app_app.post import ApiAppAppPost
from puupee-api.paths.api_app_app_upload_credentials.get import ApiAppAppUploadCredentialsGet


class AppApi(
    ApiAppAppByDeveloperGet,
    ApiAppAppByNameGet,
    ApiAppAppGet,
    ApiAppAppIdDelete,
    ApiAppAppIdGet,
    ApiAppAppIdPut,
    ApiAppAppPost,
    ApiAppAppUploadCredentialsGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
