# coding: utf-8

"""
    Puupee API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from puupee-api.paths.api_app_app_sdk.get import ApiAppAppSdkGet
from puupee-api.paths.api_app_app_sdk_id.delete import ApiAppAppSdkIdDelete
from puupee-api.paths.api_app_app_sdk_id.put import ApiAppAppSdkIdPut
from puupee-api.paths.api_app_app_sdk.post import ApiAppAppSdkPost


class AppSdkApi(
    ApiAppAppSdkGet,
    ApiAppAppSdkIdDelete,
    ApiAppAppSdkIdPut,
    ApiAppAppSdkPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
