# coding: utf-8

"""
    Puupee API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from puupee-api.paths.api_account_my_profile_change_password.post import ApiAccountMyProfileChangePasswordPost
from puupee-api.paths.api_account_my_profile.get import ApiAccountMyProfileGet
from puupee-api.paths.api_account_my_profile.put import ApiAccountMyProfilePut


class ProfileApi(
    ApiAccountMyProfileChangePasswordPost,
    ApiAccountMyProfileGet,
    ApiAccountMyProfilePut,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
