# coding: utf-8

"""
    Puupee API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from puupee-api.paths.api_app_sync_state.get import ApiAppSyncStateGet
from puupee-api.paths.api_app_sync_state_puupee_changed_eto.post import ApiAppSyncStatePuupeeChangedEtoPost


class SyncStateApi(
    ApiAppSyncStateGet,
    ApiAppSyncStatePuupeeChangedEtoPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
