# coding: utf-8

"""
    Puupee API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from puupee-api.paths.api_identity_users_lookup_by_username_user_name.get import ApiIdentityUsersLookupByUsernameUserNameGet
from puupee-api.paths.api_identity_users_lookup_count.get import ApiIdentityUsersLookupCountGet
from puupee-api.paths.api_identity_users_lookup_id.get import ApiIdentityUsersLookupIdGet
from puupee-api.paths.api_identity_users_lookup_search.get import ApiIdentityUsersLookupSearchGet


class UserLookupApi(
    ApiIdentityUsersLookupByUsernameUserNameGet,
    ApiIdentityUsersLookupCountGet,
    ApiIdentityUsersLookupIdGet,
    ApiIdentityUsersLookupSearchGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
