# coding: utf-8

"""
    Puupee API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

from puupee-api.paths.api_identity_users_assignable_roles.get import ApiIdentityUsersAssignableRolesGet
from puupee-api.paths.api_identity_users_by_email_email.get import ApiIdentityUsersByEmailEmailGet
from puupee-api.paths.api_identity_users_by_username_user_name.get import ApiIdentityUsersByUsernameUserNameGet
from puupee-api.paths.api_identity_users.get import ApiIdentityUsersGet
from puupee-api.paths.api_identity_users_id.delete import ApiIdentityUsersIdDelete
from puupee-api.paths.api_identity_users_id.get import ApiIdentityUsersIdGet
from puupee-api.paths.api_identity_users_id.put import ApiIdentityUsersIdPut
from puupee-api.paths.api_identity_users_id_roles.get import ApiIdentityUsersIdRolesGet
from puupee-api.paths.api_identity_users_id_roles.put import ApiIdentityUsersIdRolesPut
from puupee-api.paths.api_identity_users.post import ApiIdentityUsersPost


class UserApi(
    ApiIdentityUsersAssignableRolesGet,
    ApiIdentityUsersByEmailEmailGet,
    ApiIdentityUsersByUsernameUserNameGet,
    ApiIdentityUsersGet,
    ApiIdentityUsersIdDelete,
    ApiIdentityUsersIdGet,
    ApiIdentityUsersIdPut,
    ApiIdentityUsersIdRolesGet,
    ApiIdentityUsersIdRolesPut,
    ApiIdentityUsersPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
