# coding: utf-8

"""
    Puupee API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.api_app_simple_data.get import ApiAppSimpleDataGet
from openapi_client.paths.api_app_simple_data_id.delete import ApiAppSimpleDataIdDelete
from openapi_client.paths.api_app_simple_data_id.get import ApiAppSimpleDataIdGet
from openapi_client.paths.api_app_simple_data_save.post import ApiAppSimpleDataSavePost


class SimpleDataApi(
    ApiAppSimpleDataGet,
    ApiAppSimpleDataIdDelete,
    ApiAppSimpleDataIdGet,
    ApiAppSimpleDataSavePost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
