# coding: utf-8

"""
    Puupee API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from puupee-api import schemas  # noqa: F401


class TimeZone(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def iana() -> typing.Type['IanaTimeZone']:
                return IanaTimeZone
        
            @staticmethod
            def windows() -> typing.Type['WindowsTimeZone']:
                return WindowsTimeZone
            __annotations__ = {
                "iana": iana,
                "windows": windows,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["iana"]) -> 'IanaTimeZone': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["windows"]) -> 'WindowsTimeZone': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["iana", "windows", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["iana"]) -> typing.Union['IanaTimeZone', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["windows"]) -> typing.Union['WindowsTimeZone', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["iana", "windows", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        iana: typing.Union['IanaTimeZone', schemas.Unset] = schemas.unset,
        windows: typing.Union['WindowsTimeZone', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TimeZone':
        return super().__new__(
            cls,
            *args,
            iana=iana,
            windows=windows,
            _configuration=_configuration,
            **kwargs,
        )

from puupee-api.model.iana_time_zone import IanaTimeZone
from puupee-api.model.windows_time_zone import WindowsTimeZone
