# coding: utf-8

"""
    Puupee API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from puupee-api import schemas  # noqa: F401


class UserLoginInfo(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "password",
            "userNameOrEmailAddress",
        }
        
        class properties:
            
            
            class userNameOrEmailAddress(
                schemas.StrSchema
            ):
                pass
            
            
            class password(
                schemas.StrSchema
            ):
                pass
            rememberMe = schemas.BoolSchema
            __annotations__ = {
                "userNameOrEmailAddress": userNameOrEmailAddress,
                "password": password,
                "rememberMe": rememberMe,
            }
    
    password: MetaOapg.properties.password
    userNameOrEmailAddress: MetaOapg.properties.userNameOrEmailAddress
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["userNameOrEmailAddress"]) -> MetaOapg.properties.userNameOrEmailAddress: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["password"]) -> MetaOapg.properties.password: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["rememberMe"]) -> MetaOapg.properties.rememberMe: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["userNameOrEmailAddress", "password", "rememberMe", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["userNameOrEmailAddress"]) -> MetaOapg.properties.userNameOrEmailAddress: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["password"]) -> MetaOapg.properties.password: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["rememberMe"]) -> typing.Union[MetaOapg.properties.rememberMe, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["userNameOrEmailAddress", "password", "rememberMe", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        password: typing.Union[MetaOapg.properties.password, str, ],
        userNameOrEmailAddress: typing.Union[MetaOapg.properties.userNameOrEmailAddress, str, ],
        rememberMe: typing.Union[MetaOapg.properties.rememberMe, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'UserLoginInfo':
        return super().__new__(
            cls,
            *args,
            password=password,
            userNameOrEmailAddress=userNameOrEmailAddress,
            rememberMe=rememberMe,
            _configuration=_configuration,
            **kwargs,
        )
